### ISSUE TITLE
mate-panel do not show on ubuntu

### ISSUE THREAD

**Issue by perberos** [perberos/Mate-Desktop-Environment#41]
On my research, I found the follow.

When using some gtk engine, it make that widgets send a signal to a parent widget, but something do what that widget re send a signal, making a cycling of signals redrawing.

Still no luck to find the origin of the loop.

**Comment by perberos** [comment]
the issue is UBUNTU-ONLY

**Comment by paradise-os** [comment]
Well, I too have this issue--the panel refused to show itself shortly after I installed Mate. I am confused though, as to what you mean by "but something do what that widget re send a signal, making a cycling of signals redrawing."

Do you mean to say "but something does not WANT that widget to resend the signal, making a cycle of signals that keeps re-occurring?"

And also, is mate-doc-utils supposed to be at the path ~/mate-doc-utils? Is it safe for the whole Mate installation to be moved to a system location rather than my home folder? I only ask because I am trying to make an Ubuntu remix with Remastersys, and as far as I know, it does not allow for duplication of files in the home directory, which means Mate would not be included at all. Also, if Mate is meant to be located in a different place, that should be put on the wiki. I only mention this because if it must be left in the home folder, it is going to create problems with users of Distributions that are new to linux and go exploring their file system--they would be able to easily mess up the installation.

**Comment by perberos** [comment]
you look confused about how instalation works. I can suggest you use the stefano-k repo. It work very well.

try to set a non-murrine theme. nodoka works fine.

**Comment by paradise-os** [comment]
The mate panels work with some themes, but not others?

Regarding the repo: that would mean installing Mate over again, yes? Isn't that repo still largely incomplete?

**Comment by perberos** [comment]
This issue was fixed (indirectamente...)

https://github.com/perberos/Mate-Desktop-Environment/issues/52
