### ISSUE TITLE
mate-panel opens nautilus and not caja

### ISSUE THREAD

**Issue by ghost** [perberos/Mate-Desktop-Environment#46]
See title.  I'm using the Arch Linux repo, if that helps.

**Comment by hubertlepicki** [comment]
I think this has something to do with preferred applications. Tried to look around the code, but couldn't find out how this mechanizm works -- maybe someone more competent than me can help.

On Linux Mint, uninstalling Nautilus (or whole Gnome 3) helps -- Caja starts as expected.

**Comment by ghost** [comment]
Well, that's still a bit of a problem, because GNOME and Mate shouldn't conflict with each other.

I think that this might help, only, replace Thunar with Caja: https://help.ubuntu.com/community/DefaultFileManager

**Comment by hubertlepicki** [comment]
Okay. So, the problem looks like this: Mate and Gnome share the same default applications list file. On my system, it's symlink in /usr/share/applications/defaults.list that leads to /etc/gnome/defaults.list. File nautilus.desktop is bound there as default file manager file. When replaced with caja.desktop that one should launch it.

Now, I think that we might as well create our own defaults.list, say mate-defaults.list and use this one instead of Gnome's.

This, however, also means we need to patch xdg-open utility so that links clicked in different apps are handled properly etc.

**Comment by ghost** [comment]
Oddly enough, I don't have /usr/share/applications/defaults.list nor /etc/gnome/defaults.list; I think that that's some Ubuntu/Mint-specific file.  What are its contents?

**Comment by hubertlepicki** [comment]
It's something like that:
$ cat /usr/share/applications/defaults.list 
[Default Applications]
...
inode/directory=nautilus.desktop
...

and you can also override individual entries with file ~/.local/share/applications/defaults.list

I still don't know what's the right way to customize it for Mate, just wondering how lxde does it...

**Comment by perberos** [comment]
this was fixed.

https://github.com/mate-desktop/mate-control-center/commit/06d81df2871a25a93cdf7cffaf87f5cd4f15fe84
